### ISSUE TITLE
driving past the start results in an endless mode

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/gravity-derby#1]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7360266/113892352-32691b80-97c6-11eb-8876-b49ada784421.png">

EXP:  level will end
OBS: driving past the start results in an endless mode
FRQ: 100%
REP: equip items
drive past the start
fall of the edge
fall indefinitely

**Comment by Oskmos** [comment]
Fixed the level so it has a big wall in the end. (also added some extra slopes and bumps so the level is a bit longer than before)
